apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myconatiner3
          image: lakshmankumar12345/newimage # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
